In [1]:
#missing indicator

import numpy as np 
import pandas as pd 

In [2]:
from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [3]:
df = pd.read_csv("titanic_toy",usecols=['Age','Survived'])

In [4]:
df.head()

Age  Survived
0  22.0         0
1  38.0         1
2  26.0         1
3  35.0         1
4  35.0         0

In [5]:
df.isnull().mean()*100

Age         19.86532
Survived     0.00000
dtype: float64

In [6]:
x = df.drop(['Survived'],axis=1)
y = df['Survived']

In [7]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [8]:
x_train.head()

Age
30   40.0
10    4.0
873  47.0
182   9.0
876  20.0

In [9]:
# relpace with mean value .

si = SimpleImputer()
x_train_trf = si.fit_transform(x_train)
x_test_trf  = si.transform(x_test)

In [10]:
x_train_trf

array([[40.        ],
       [ 4.        ],
       [47.        ],
       [ 9.        ],
       [20.        ],
       [30.        ],
       [30.        ],
       [13.        ],
       [36.        ],
       [29.78590426],
       [31.        ],
       [38.        ],
       [18.        ],
       [29.78590426],
       [25.        ],
       [37.        ],
       [18.        ],
       [35.        ],
       [46.        ],
       [70.5       ],
       [48.        ],
       [48.        ],
       [24.        ],
       [56.        ],
       [54.        ],
       [29.78590426],
       [16.        ],
       [34.        ],
       [29.78590426],
       [43.        ],
       [ 2.        ],
       [50.        ],
       [60.        ],
       [41.        ],
       [ 3.        ],
       [39.        ],
       [33.        ],
       [29.78590426],
       [29.78590426],
       [37.        ],
       [42.        ],
       [19.        ],
       [16.        ],
       [29.78590426],
       [24.        ],
       [45

In [11]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf , y_train)

y_pred = clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.5586592178770949

In [12]:
mi = MissingIndicator()

mi.fit(x_train)

MissingIndicator()

In [13]:
mi.features_

array([0], dtype=int64)

In [14]:
x_train_missing = mi.transform(x_train)

In [15]:
x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [16]:
x_test_missing = mi.transform(x_test)

In [17]:
x_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [18]:
x_train['Age_NA'] = x_train_missing

In [19]:
x_test

Age
707  42.0
37   21.0
615  24.0
169  28.0
68   17.0
..    ...
89   24.0
80   22.0
846   NaN
870  26.0
251  29.0

[179 rows x 1 columns]

In [20]:
x_test['Age_NA'] = x_test_missing

In [21]:
x_train

Age  Age_NA
30   40.0   False
10    4.0   False
873  47.0   False
182   9.0   False
876  20.0   False
..    ...     ...
534  30.0   False
584   NaN    True
493  71.0   False
527   NaN    True
168   NaN    True

[712 rows x 2 columns]

In [22]:
si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.fit_transform(x_test)

In [23]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2 , y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.5586592178770949

In [28]:
# To do this in simpleimputer (add_indicator = True) , 
# apde missing indicator ne call karvani and extra work karvu na pade. 

In [24]:
si = SimpleImputer(add_indicator=True)

In [25]:
x_train = si.fit_transform(x_train)

In [26]:
x_test = si.transform(x_test)

In [27]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2 , y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.5586592178770949

In [ ]:
# the end . 